### ISSUE TITLE
Can This Replace @extend ?

### ISSUE THREAD

**Issue by wesleyboar** [eriklharper/postcss-nested-import#17]
I use https://github.com/travco/postcss-extend, which is an old and unmaintained software.

I need a replacement. Can `@nested-import` serve as a replacement?

I think it can **not** do so without major overhead. I know everything I `@extend` would become `@nested-import`, but I would now need to import files, not pieces of files, so I would need to make as many files as I have unique instances of `@extend`.... right?

**Comment by revelt** [comment]
You're right, the imports will plunk the [whole file](https://github.com/eriklharper/postcss-nested-import/blob/1250bed2cef995e942b44672d1ad5a4bd460eed3/index.js#L44), straight from `fs.readFileSync`.

On the other hand, looking pragmatically, from the KPI's, web vitals perspective, redundant CSS is the least harmful of anything redundant — JS is the evil, that one is slow and needs tree-shaken and otherwise optimised.

I know I'm being a hypocrite (having authored `email-comb` the unused CSS remover) =]

**Comment by wesleyboar** [comment]
I don't mind repeat CSS in the output. It's the tons of tiny files to maintain that would vex me.

_In fact, `@extend` hoisting my code to a single selector causes me grief in my project that offers both large global stylesheets and small independent clients for clients, because ii large stylesheets I fear mis-ordering of CSS and the smaller files include irrelevant classes (etc.) in its selectors._

**Comment by wesleyboar** [comment]
So, what is a good use case for `@nested-import`? (Importing a stylesheet that sometimes needs to be in a different `layer()`?) Would a list of use cases be good for the README?

**Comment by revelt** [comment]
Originally, I picked postcss for my website, I don't remember what I needed this library for but probably for dark/light themes or resets or something. Eventually, I pushed it to the limit and got fed up with postcss and switched to good old SASS monolith, one file, all custom and hand-written (like back in the day). At day jobs everybody around me is using tailwind, of course.

**Comment by wesleyboar** [comment]
Hm, I can see the dark/light/other-a11y-type use case. Isolate the styles for each. Then load them into one stylesheet who only has one job, to output the correct styles.

I'll keep this plugin on my list of maybes. I'm still a PostCSS fanboy.
